### ISSUE TITLE
Custom file layout always fails with error

### ISSUE THREAD

**Issue by avdel** [njh/rotter#29]
Hello,

After making the roter-master branch, I noticed that it always complains with "Failed to build file path for layout".

It seems that the problem is in rotter.c (line 270) where the if condition must not be terminated with a colon. The current master branch version as is now always return an error.

Please verify and act accordingly

Thank you for this nice implementation

**Comment by njh** [comment]
It looks like #34 fixed this, thanks @paraenggu
