### ISSUE TITLE
Install on RPI3

### ISSUE THREAD

**Issue by kylelmartin** [njh/rotter#33]
Probably not an issue other than me being a noob.

I'm trying to install this and silentjack on a Raspberry Pi 3. 
I've both downloaded and cloned the package.
For giggles I (re)installed automake.

./configure returns "no such file or directory"

./autogen.sh && make && sudo make install 
gets me a little further but won't recognize the modern version of jack (from what I can tell, perhaps I'm installing in the wrong place.)

These are two very cool tools I would like to use. If you're not maintaining this project any longer can you tell me what people are using now instead of your jack scripts?
Any help would be greatly appreciated.

**Comment by njh** [comment]
Did you get this working?

./configure is used to setup the tar.gz file download from the official release:
https://www.aelius.com/njh/rotter/

./autogen.sh is used it configure when checking out from Git. But you must have autoconf/automake installed on your system for it to work.

I am not aware of any problems with rotter working with recent versions of Jack. The API has not changed in a very long time.

What would be really good is if someone write a 'How To' or 'Getting Started' guide.

**Comment by njh** [comment]
No response, so closing issue.
